### ISSUE TITLE
Sigs update ?

### ISSUE THREAD

**Issue by skullcheat** [luizpalazzo/apex_linux#2]
I would like to know if you can provide the Signs of the new update thank you (no one has yet shared on UC)
dwLocalPlayer
dwBullletSpeed

**Comment by luizpalazzo** [comment]
Hi, unfortunally i dont have the new signatures, i am trying to hardcode the offsets instead of using the signatures, but i dont have much time to do it.

**Comment by luizpalazzo** [comment]
Hi, i updated the offsets instead of signatures.
